version: '3'

services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'db'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/ProgramadoroTracker'
      - 'box:/box'
    stdin_open: true
    tty: true

  box:
    image: busybox
    volumes:
      - box:/box

volumes:
  postgres:
  box: